#!/usr/bin/env bash
# write a Bash script that displays only the lines containing the word bash. This will help you easily identify the PID of your Bash process.
ps aux | grep "bash"
# shellcheck disable=SC2009