#!/usr/bin/env bash
# to ensure you understand and can use the SIGKILL signal to forcibly terminate a process, even one designed to be “invincible” to SIGTERM.
pgrep -f 7-highlander | xargs -r kill -9
