#!/usr/bin/env bash
# Displays “Best School” 10 times. However, for the 9th ite# ration, your script should display “Best School” and then# on a new line, display “Hi”

count=1;
while [ "$count" -le 10 ]
do 
    if [ "$count" -eq 4 ]
    then
	echo "bad luck";
   
    elif [ "$count" -eq 8 ]
    then
	echo "good luck";
   else 
       echo "Best School";
     fi
    count=$(( count+1 ));
done
