#!/usr/bin/env bash
#script that provides information about a file named school. Your script should per#form the following checks and print the corresponding messages:

if [ -e school ]; then
    echo "school file exists"
   
else
   echo "school file does not exist"
fi

if [  ! -s school ]; then
    echo "school file is empty"
else
    echo "school file is not empty"
fi

if [ -f school ]; then
    echo "school is a regular file"
fi
